name: Build-APK

on:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade flet flet-cli   # ✅ تثبيت flet-cli

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build APK
        run: |
          flutter config --no-analytics
          flet build apk --verbose \
            --build-number=${{ github.run_number }} \
            --build-version=1.0.${{ github.run_number }}

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-build-artifact
          path: build/apk
          if-no-files-found: warn
